### ISSUE TITLE
Issue with reset password on calendarific.com

### ISSUE THREAD

**Issue by constantinadrian** [pinkywafer/Calendarific#18]
Is someone still maintain the calendarific.com. I have been reset my password on the site with the reset link provided on email but still can login into my account as I still get the error message _"Invalid email or password. Please try again. "_ and now I'm not able to use my API key. 
If I register again says that email _Guess what? You already have an account with us! Login or reset your password to gain access to you account _
I also email to _support@calendarific.com_ and _yourfriends@calendarific.com_ but with no success.
Is this a bug in application on the reset password.

**Comment by pinkywafer** [comment]
I can't help with this I'm afraid. I'm not part of the calendarific team. 
I am not using the calendarific python library, only because it is out of date. I think the repo gas been updated, but still no release published. See https://github.com/calendarific/python-calendarific/issues/3
I haven't seen any recent activity on this repo, so unsure what's going on over there. I have also previously emailed them, and also have received no reply.
Sorry I'm unable to help with this at the moment

**Comment by constantinadrian** [comment]
thank you for the replay. I was using calendarific python library for an educational project and was enough for me. Anyway I manage to get another reset link on my email and set up different password. It looks like I was using some special characters in my password that I was not supposed to. Now is fine
